# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    make.sh                                            :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: youskim <youskim@student.42seoul.k>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/28 15:06:10 by youskim           #+#    #+#              #
#    Updated: 2022/03/28 18:45:04 by youskim          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = push_swap
CC = gcc
W = -Wall -Wextra -Werror
FILE = push_swap.c lst_first.c lst_stack.c algorithm.c algorithm2.c ft_atoi.c newstack.c operation_a.c operation_b.c

all : $(NAME)

$(NAME) : $(FILE)
	$(CC) $(W) $^
